spring:
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      fail-on-empty-beans: false
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        use_sql_comments: true


logging:
  level:
    com:
      example:
        blogsearch:
          external:
            feign:
              client:
                KakaoFeignClient: DEBUG

external:
  api:
    url:
      kakao: https://dapi.kakao.com
      naver: https://openapi.naver.com

