spring:
  profiles:
    include: API-KEY
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
      fail-on-empty-beans: false
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    host: localhost
    port: 6379

logging:
  level:
    com:
      example:
        blogsearch:
          external:
            feign:
              client:
                KakaoFeignClient: DEBUG
                NaverFeignClient: DEBUG

external:
  api:
    url:
      kakao: https://dapi.kakao.com
      naver: https://openapi.naver.com